#!/bin/bash

FILEPATH=/etc/dhcpcd.conf


#~ /usr/src/b2ei-energy-monitor/ipconfig --static 192.168.1.1/16 192.168.1.2 192.168.1.3 192.168.1.4 8.8.8.8
#~ /usr/src/b2ei-energy-monitor/ipconfig --dhcp

if [ "$1" = '--static' ]; then
        if [[ $(echo  $2  | grep -c "^[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\/\(16\|17\|18\|19\|20\|21\|22\|23\|24\|25\|26\|27\|28\|29\|30\)\{1\}$") -eq 1 ]] ; then
                if [[ $(echo  $3  | grep -c "^[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}$") -eq 1 ]] ; then         
                        if [[ $(echo  $4  | grep -c "^[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}$") -eq 1 ]] ; then
                                NAMESERVER=$4
                                if [[ $(echo  $5  | grep -c "^[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}$") -eq 1 ]] ; then
                                        NAMESERVER=$NAMESERVER" "$5
                                fi
                                if [[ $(echo  $6  | grep -c "^[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}$") -eq 1 ]] ; then
                                        NAMESERVER=$NAMESERVER" "$6
                                fi
                                cp $FILEPATH $FILEPATH"."`date +"%s"`".bak"
                                echo "hostname
clientid
persistent
option rapid_commit
option domain_name_servers, domain_name, domain_search, host_name
option classless_static_routes
option ntp_servers
option interface_mtu
require dhcp_server_identifier
slaac private
profile static_eth0
static ip_address=192.168.0.2/24
static routers=192.168.0.1
static domain_name_servers=192.168.0.1 8.8.8.8 8.8.4.4
interface eth0
static ip_address="$2"
static routers="$3"
static domain_name_servers="$NAMESERVER"
fallback static_eth0
" > $FILEPATH
                                echo 'ok'
                        else
                                echo "fail"
                        fi
                else
                        echo "fail"
                fi
        else
                echo "fail"
        fi
else
        if [ "$1" = '--dhcp' ]; then
			cp $FILEPATH $FILEPATH"."`date +"%s"`".bak"
			echo "hostname
clientid
persistent
option rapid_commit
option domain_name_servers, domain_name, domain_search, host_name
option classless_static_routes
option ntp_servers
option interface_mtu
require dhcp_server_identifier
slaac private
profile static_eth0
static ip_address=192.168.0.2/24
static routers=192.168.0.1
static domain_name_servers=192.168.0.1 8.8.8.8 8.8.4.4
interface eth0
fallback static_eth0
" > $FILEPATH
			echo 'ok'
        else
			if [ "$1" = '--reboot' ]; then
		                echo 'ok'
				(sleep 1; reboot now)&
			else
				if [ "$1" = '--shutdown' ]; then
					echo 'ok'
					(sleep 1; shutdown now)&
				else
					if [ "$1" = '--update' ]; then
						touch /usr/src/b2ei-energy-monitor/.require-update
						echo 'ok'
					else
						cat $FILEPATH
					fi
				fi
			fi
        fi
fi





